# github 发布 阿里云
# https://juejin.cn/post/7157193707693801508
# https://juejin.cn/post/6931318429420879879
# https://juejin.cn/post/7264062850200698938

name: Deploy to Server
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.ALIYUN_SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: SSH connection to server
        uses: wmasfoe/talk@master
        with:
          # aliy IP
          host: ${{ secrets.ALIYUN_SERVER_HOST }}
          username: root
          # aliy root 用户的登录密码
          password: ${{ secrets.ALIYUN_SERVER_ROOT_PWD }}
          # aliy 生成的 私钥，公钥在 github ssh
          key: ${{ secrets.ALIYUN_SERVER_PRIVATE_KEY }}
          script: |
            mkdir ~/project
            cd ~/project/talk
            source ~/.nvm/nvm.sh
            source ~/.bash_profile
            nvm use 18
            git pull 
            npm i 
            pm2 start start.js --name talk
            pm2 reload talk
